#
#   __          __  _                          __  __
#   \ \        / / | |                        |  \/  |
#   \ \  /\  / /__| | ___ ___  _ __ ___   ___| \  / |___  __ _
#   \ \/  \/ / _ \ |/ __/ _ \| '_ ` _ \ / _ \ |\/| / __|/ _` |
#   \  /\  /  __/ | (_| (_) | | | | | |  __/ |  | \__ \ (_| |
#   \/  \/ \___|_|\___\___/|_| |_| |_|\___|_|  |_|___/\__, |
# 1.0.1                                                __/ |
# By Nenfal                                           |___/
# https://github.com/MatthieuClaessens/WelcomeMessage

toggle-welcome-message: true

welcome-message: "§eWelcome §6%player% §eto the server!"

join-message: "§a+ §6%player% §7joined the server"
quit-message: "§c- §6%player% §7left the server"