#################################################################
#+--------------------------------------------------------------+
#|   __          __  _                          __  __          |
#|   \ \        / / | |                        |  \/  |         |
#|   \ \  /\  / /__| | ___ ___  _ __ ___   ___| \  / |___  __ _ |
#|   \ \/  \/ / _ \ |/ __/ _ \| '_ ` _ \ / _ \ |\/| / __|/ _` | |
#|   \  /\  /  __/ | (_| (_) | | | | | |  __/ |  | \__ \ (_| |  |
#|   \/  \/ \___|_|\___\___/|_| |_| |_|\___|_|  |_|___/\__, |   |
#| 1.0                                               __/ |      |
#| By Nenfal                                        |___/       |
#+--------------------------------------------------------------+
#################################################################

join-message: "§a+ §6%player% §7joined the server"
quit-message: "§c- §6%player% §7left the server"