name: WelcomeMessage
version: 1.0
main: org.welcomemessage.WelcomeMessage
api-version: 1.21

commands:
  wmreload:
    description: Reload the plugin configuration.
    usage: /wmreload
    permission: welcomemessage.reload
    permission-message: You do not have permission to reload the config.